11 modbus tcp
lsd-maddrive/Awesome_TAU_Stand pull request #12
Opened 2022-07-25 17:03 UTC by Briergo

2022-07-28 21:48 UTC, Doraepod requested changes
Много стилистических ошибок, которые надо поправить. По существу понял мало, надо обсудить.

2022-07-28 21:48 UTC, Doraepod commented on README.md
> +## Как пользоваться Modbus TCP на STM32F767ZI.
Не надо изменять инструкцию по работе над проектом. Описание модуля находится в папке модуля, либо в /docs в отдельной папке

2022-07-28 21:48 UTC, Doraepod commented on docs/README.md
> +
Readme в /docs тоже общий. Описание каждого модуля должно быть в уникальной папке

2022-07-28 21:48 UTC, Doraepod commented on docs/picture/name.txt
> +Hello
Это нужно?

2022-07-28 21:48 UTC, Doraepod commented on firmware/README.md
> -### TARGET
Это полезный файл, его не надо удалять

2022-07-28 21:48 UTC, Doraepod commented on firmware/include/modbusTCP/modbusFunc.h
> +int modbustcp_send_answer_fun_0x01(int tid, int pid, char uid, char func, int count);
Не стоит пользоваться неопределенными типами. int может быть разный, в зависимости от платформы. Используйте int16_t, если подразумевается он

2022-07-28 21:48 UTC, Doraepod commented on firmware/src/modbusTCP/modbusFunc.c
> +extern char out_buf[100];
Слишком общее имя. Высокая вероятность достать экстерном не то

2022-07-28 21:48 UTC, Doraepod commented on firmware/src/modbusTCP/modbusFunc.c
> +int modbustcp_send_answer_fun_0x04(int tid, int pid, char uid, char func, int counter)
Не понимаю что происходит, надо будет обсудить. Не лучше ли сделать одну универсальную функцию, которая принимает операцию, которую надо сделать? А то все функции ниже выглядят очень похоже.

2022-07-28 21:48 UTC, Doraepod commented on firmware/src/modbusTCP/modbusRegister.c
> +{
Точно надо выделять память динамически? Это не может быть статический массив?

2022-07-28 21:48 UTC, Doraepod commented on firmware/src/modbusTCP/modbusRegister.c
> +{
Да и вообще, зачем все-таки структура? Надо менять местами элементы? Почему не массив?

2022-07-28 21:48 UTC, Doraepod commented on firmware/src/modbusTCP/modbusTCP.c
> +#include <lwip/netif.h>
Не пишите/убирайте русские комментарии, происходит такое

2022-07-28 21:48 UTC, Doraepod commented on firmware/src/modbusTCP/modbusTCP.c
> +    case 0x04:
Что такое 0x04? Если эти значения определены протоколом используйте дефайны

2022-08-07 08:29 UTC, Briergo commented
Исправил имена функций, переработал регистры и написал тест.

2022-08-12 15:08 UTC, Doraepod approved these changes

2022-08-12 15:08 UTC, merged