14 encoder
lsd-maddrive/Awesome_TAU_Stand pull request #16
Opened 2022-08-11 17:21 UTC by nikef84

Написаны два новых си и два заголовочных фала, для работы с энкодером.
Тест can_test - новый, работает с написанными библиотеками. can_test_2 - прошлый тест (он работал).
Немного подправил комментарии в файлах к датчику тока и немного поменял инклюды библиотек и оформление кода.

2022-08-22 15:33 UTC, Doraepod requested changes

2022-08-22 15:33 UTC, Doraepod commented on firmware/include/lld_i2c.h
> +#include <common.h>
Все должно быть внутри #ifndef #endif

2022-08-22 15:33 UTC, Doraepod commented on firmware/include/sensor_m3421.h
> +
Все должно быть внутри #ifndef #endif

2022-08-22 15:33 UTC, Doraepod commented on firmware/include/terminal_write.h
> +
Все должно быть внутри #ifndef #endif

2022-08-22 15:33 UTC, Doraepod commented on firmware/src/can_lld.c
> +// @brief   Setting the can configuration
Напишите что эти настройки означают. Самое важное - частота и ее расчет

2022-08-22 15:33 UTC, Doraepod commented on firmware/src/encoder.c
> +      absoluteEncoderAngleOfRotation(); // Measures the rotation angle within one turn.
Имена функций не очевидны. Так же эти функции не могут быть вызваны откуда либо кроме как из этого файла. В этом случае можно убрать их определение из .h и написать другим стилем, например через подчеркивание. Функции могут читать данные с датчика, а могу считать по уже известным значениям. Можно это учитывать в названиях, например read_angle(), calculate_speed().

2022-08-22 15:33 UTC, Doraepod commented on firmware/src/encoder.c
> +  return absoluteEncoder.NumberOfTurns;
Функция должна возвращать int32_t

2022-08-22 15:33 UTC, Doraepod commented on firmware/src/encoder.c
> +#include <encoder.h>
Переименуйте файл в абсолютный энкодер

2022-08-22 15:45 UTC, Doraepod commented on firmware/src/encoder.c
> +  txbuf.data8[3] = 0x00;
Поправить комментарий и добавить дефайн для 0x00

2022-08-22 18:54 UTC, nikef84 commented on firmware/src/can_lld.c
> +// @brief   Setting the can configuration
не особо понимаю что здесь писать. вставил что-то из даташита

2022-08-25 15:47 UTC, Doraepod requested changes
Вроде все работает, поправьте пару моментов и можно сливать.

2022-08-25 15:47 UTC, Doraepod commented on firmware/src/absolute_encoder.c
> +  if (abs(absoluteEncoder.NumberOfTurns) < 100){ // Reads data from the encoder.
Задефайните 100

2022-08-25 15:47 UTC, Doraepod commented on firmware/src/absolute_encoder.c
> +  else absoluteEncoder.MultiTurnAngleOfRotation = 360 * absoluteEncoder.NumberOfTurns - (360 - absoluteEncoder.AngleOfRotation);
Здесь else фактически означает (< -100), напишите это условием для читаемости. 100, разумеется, тоже должно быть дефайном.

2022-08-25 15:47 UTC, Doraepod commented on firmware/src/absolute_encoder.c
> +  txbuf.data8[2] = CAN_TXBUF_VELOCITY_BYTE; // Makes necessary configuration.
Добавьте определение направления скорости. Можно смотреть на изменение multi-turn angle.

2022-08-25 19:34 UTC, nikef84 commented on firmware/src/absolute_encoder.c
> +  txbuf.data8[2] = CAN_TXBUF_VELOCITY_BYTE; // Makes necessary configuration.
А оно же уже есть.
`if (absoluteEncoder.NumberOfTurns < 0)absoluteEncoder.RotationalSpeed = -absoluteEncoder.RotationalSpeed;//Take into account the sign.`

2022-08-25 20:17 UTC, Doraepod commented on firmware/src/absolute_encoder.c
> +  txbuf.data8[2] = CAN_TXBUF_VELOCITY_BYTE; // Makes necessary configuration.
Проглядел, но это не правильно работает. В этом случае если сделать несколько оборотов в минус, а потом закрутить в положительном направлении скорость все еще будет отрицательная. Нужно что то вроде w = w * sign(phi - phi_prev). Но функции sign нет, так что через условие

2022-08-28 16:25 UTC, Doraepod requested changes

2022-08-28 16:25 UTC, Doraepod commented on firmware/src/absolute_encoder.c
> +  else dbgPrintf("Absolute encoder thread has NOT been stopped");
Не надо писать в терминал, это только для тестов. Про сообщения я имел в виду возвращать значение, которое отдает chThdWait()

2022-08-29 01:03 UTC, Doraepod requested changes

2022-08-29 01:03 UTC, Doraepod commented on firmware/src/absolute_encoder.c
> +  canSimpleUninit();
return завершает выполнение функции. Последняя строчка не выполняется.

2022-08-29 13:18 UTC, Doraepod approved these changes

2022-08-29 13:27 UTC, merged